# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZRijCnOa1hMzlyTXK7tcBjiirbdzCk7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import apyori as apriori

df = pd.read_csv('CanteenDataSet.csv')
df.head()

df.rename(columns = {'Tea, Samosa, Sandwich': 'Items'} , inplace = True)
df.head()

df['Items'].str.split(",")

df= df['Items'].str.split(",", expand= True)
df.rename(columns={0: 'Item1', 1:'Item2', 2:'Item3', 3:'Item4'}, inplace = True)

df.head()

records = []
for i in range(19):
  records.append([str(df.values[i,j]) for j in range(0,4)])

print(type(records))

from mlxtend.frequent_patterns import apriori, association_rules

items = set()
for col in df:
  items.update(df[col].unique())
print(items)

itemset = set(items)

encoded_value = []
for index, row in df.iterrows():
  rowset = set(row)
  labels = {}
  uncommons = list(itemset- rowset)
  commons = list(itemset.intersection(rowset))
  for uc in uncommons:
    labels[uc] = 0
  for com in commons:
    labels[com] = 1
  encoded_value.append(labels)
encoded_value[0]
df1 = pd.DataFrame(encoded_value)

frequent = apriori(df1, min_support = 0.2, use_colnames=True)

frequent.head(7)

rules = association_rules(frequent, metric= 'confidence', min_threshold = 0.6)

rules.head()

